import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:lifeos/models/task.dart';
import 'package:lifeos/models/note.dart';
import 'package:lifeos/models/expense.dart';
import 'package:lifeos/models/habit.dart';
import 'package:lifeos/models/inbox_item.dart';
import 'package:lifeos/app.dart';
import 'package:lifeos/services/ai_fix_store.dart';
import 'package:lifeos/services/deen_notifications.dart';
import 'package:lifeos/services/shared_inbox.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  Hive.registerAdapter(TaskAdapter());
  Hive.registerAdapter(NoteAdapter());
  Hive.registerAdapter(ExpenseAdapter());
  Hive.registerAdapter(HabitAdapter());
  Hive.registerAdapter(InboxItemAdapter());
  await AiFixStore.init();
  await Hive.openBox<Task>('tasks');
  await Hive.openBox<Note>('notes');
  await Hive.openBox<Expense>('expenses');
  await Hive.openBox<Habit>('habits');
  await Hive.openBox<InboxItem>('inbox');
  await Hive.openBox('qr_history');
  await Hive.openBox('nova_history');
  await Hive.openBox('notes_media');
  await Hive.openBox('note_meta');
  await Hive.openBox('notes_versions');
  await Hive.openBox('clipboard');
  await Hive.openBox('money_settings');
  await Hive.openBox('settings');
  await Hive.openBox('ai_trees');
  await Hive.openBox('debts');
  await Hive.openBox('prices');
  await Hive.openBox('market_items');
  await Hive.openBox('shopping_list');
  await Hive.openBox('inventory');
  await Hive.openBox('deen_settings');
  await Hive.openBox('salah_log');
  await Hive.openBox('amal_log');
  await Hive.openBox('tasbih_session');
  await Hive.openBox('deen_meta');
  await Hive.openBox('memorization');
  await Hive.openBox('deen_arabic');
  await DeenNotifications.init();
  await DeenNotifications.rescheduleAll();
  await initializeDateFormatting('bn');
  SharedInbox.startMonitoring();
  runApp(const LifeOSApp());
}
